import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..', '..');

function parseBoolean(value: string | undefined, fallback: boolean): boolean {
  if (value === undefined) {
    return fallback;
  }
  return ['1', 'true', 'yes', 'on'].includes(value.toLowerCase());
}

function parseHeadersJson(raw: string | undefined): Record<string, string> {
  if (!raw) {
    return {};
  }

  try {
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    return Object.fromEntries(
      Object.entries(parsed).filter(([, value]) => typeof value === 'string') as Array<
        [string, string]
      >,
    );
  } catch {
    return {};
  }
}

export const appConfig = {
  port: Number(process.env.PORT || 3210),
  host: process.env.PETTANGATARI_HOST || process.env.HOST || '127.0.0.1',
  frontendDistPath: path.resolve(projectRoot, 'frontend', 'dist'),
  rootDataPath: path.resolve(projectRoot, 'data'),
  fileCharactersPath: path.resolve(projectRoot, 'data', 'characters'),
  fileScenesPath: path.resolve(projectRoot, 'data', 'scenes'),
  fileStoreIndexPath: path.resolve(projectRoot, 'data', 'index.json'),
  studioStatePath: path.resolve(projectRoot, 'backend', 'data', 'studio-state.json'),
  exampleAutogenConfigPath: path.resolve(projectRoot, 'backend', 'example-autogen-config.json'),
  packageOutputPath: path.resolve(projectRoot, 'backend', 'data', 'packages'),
  autogeneratedSpritesPath: path.resolve(projectRoot, 'backend', 'data', 'Autogenerated Sprites'),
  comfyUi: {
    baseUrl: process.env.COMFYUI_BASE_URL || 'http://127.0.0.1:8188',
    connectionSettingsPath: path.resolve(projectRoot, 'backend', 'data', 'comfyui-connection.json'),
    spriteWorkflowPath: path.resolve(projectRoot, 'frontend', 'src', 'guide', 'SpriteGenWorkflow.json'),
    spriteOpenMouthWorkflowPath: path.resolve(projectRoot, 'frontend', 'src', 'guide', 'SpriteGenWorkflowOpenMouth.json'),
    cgWorkflowPath: path.resolve(projectRoot, 'frontend', 'src', 'guide', 'CgGenWorkflow.json'),
    modelsPath: process.env.COMFYUI_MODELS_PATH || '',
  },
  sillyTavern: {
    connectionSettingsPath: path.resolve(projectRoot, 'backend', 'data', 'sillytavern-connection.json'),
    baseUrl: process.env.SILLYTAVERN_BASE_URL || 'http://127.0.0.1:8000',
    charactersEndpoint: process.env.SILLYTAVERN_CHARACTERS_ENDPOINT || '/api/characters/all',
    generateEndpoint:
      process.env.SILLYTAVERN_GENERATE_ENDPOINT || '/api/backends/chat-completions/generate',
    sessionGenerateEndpoint: process.env.SILLYTAVERN_SESSION_GENERATE_ENDPOINT || '',
    statusEndpoint:
      process.env.SILLYTAVERN_STATUS_ENDPOINT || '/api/backends/chat-completions/status',
    settingsEndpoint: process.env.SILLYTAVERN_SETTINGS_ENDPOINT || '/api/settings/get',
    defaultChatCompletionSource: process.env.SILLYTAVERN_CHAT_COMPLETION_SOURCE || 'unknown',
    defaultModel: process.env.SILLYTAVERN_MODEL || '',
    streamingDefault: parseBoolean(process.env.SILLYTAVERN_STREAMING_DEFAULT, true),
    headers: parseHeadersJson(process.env.SILLYTAVERN_HEADERS_JSON),
  },
  shutdownToken: process.env.PETTANGATARI_SHUTDOWN_TOKEN || '',
};
