import express from 'express';
import { spawn } from 'node:child_process';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import JSZip from 'jszip';
import { appConfig } from '../config.js';
import {
  generateComfyDepthMapAndSave,
  generateComfyImageAndSave,
  getComfyGenerationOptions,
  getComfyStatus,
} from '../comfy/client.js';
import { getComfyBaseUrl, normalizeComfyBaseUrl, setComfyBaseUrl } from '../comfy/connectionSettings.js';
import { SillyTavernClient } from '../sillytavern/client.js';
import type { SillyTavernCharacter } from '../sillytavern/types.js';
import {
  addPackageRecord,
  createRun,
  deleteRun,
  deletePackageAndLinkedContent,
  deleteScenario,
  deleteStudioCharacter,
  getStudioState,
  saveUploadedStudioAsset,
  updateStudioArtStylePresets,
  updateRunMessages,
  upsertScenario,
  upsertStudioCharacter,
} from '../studio/store.js';
import {
  DEFAULT_CHARACTER_AUTOMATIC_GENERATION,
  SPRITE_EXPRESSIONS,
  type CharacterAutomaticGenerationRecord,
  type ScenarioRunMessage,
  type SceneWeatherPreset,
  type StudioCharacterRecord,
} from '../studio/types.js';

const router = express.Router();
const sillyTavernClient = new SillyTavernClient();
const MAX_ASSET_VARIANTS = 10;
const KEEP_CHARACTER_ASSET_TOKEN = '__PETTANGATARI_KEEP_CHARACTER_ASSET__';
const LEGACY_KEEP_CHARACTER_ASSET_TOKEN = '__SILLYVN_KEEP_CHARACTER_ASSET__';
const CHARACTER_MANIFEST_FILE = 'character.json';
const SCENARIO_MANIFEST_FILE = 'scenario.json';
const PACKAGE_METADATA_FILE = 'pettangatari-package.json';
const LEGACY_PACKAGE_METADATA_FILE = 'sillyvn-package.json';
const SILLY_TAVERN_CHARACTER_CARD_FILE = 'sillytavern/lead-character-card.json';
const SCENE_WEATHER_PRESETS = new Set<SceneWeatherPreset>([
  'none',
  'rain',
  'thunderstorm',
  'fog',
  'snow',
  'sakura-petals',
  'autumn-leaves',
]);

function resolveGeneratedAssetPathForDeletion(filePath: string): string | null {
  const trimmedPath = filePath.trim();
  if (!trimmedPath) {
    return null;
  }

  const generatedRoot = path.resolve(appConfig.autogeneratedSpritesPath);
  const resolvedPath = path.resolve(trimmedPath);
  const relativePath = path.relative(generatedRoot, resolvedPath);
  if (!relativePath || relativePath.startsWith('..') || path.isAbsolute(relativePath)) {
    return null;
  }

  return resolvedPath;
}

function shouldUseCompactCharacterResponse(request: express.Request): boolean {
  return request.query.compact === '1' || request.query.compact === 'true';
}

function toCompactCharacterResponse(character: StudioCharacterRecord): Pick<StudioCharacterRecord, 'id' | 'createdAt' | 'updatedAt'> {
  return {
    id: character.id,
    createdAt: character.createdAt,
    updatedAt: character.updatedAt,
  };
}

router.get('/state', async (_request, response) => {
  try {
    const state = await getStudioState();
    response.json(state);
  } catch (error) {
    response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to load studio state.',
    });
  }
});

router.put('/artstyle-presets', express.json({ limit: '50mb' }), async (request, response) => {
  try {
    const rawPresets = Array.isArray(request.body?.artStylePresets) ? request.body.artStylePresets : [];
    const presets = rawPresets
      .filter((entry: unknown): entry is Record<string, unknown> => Boolean(entry && typeof entry === 'object'))
      .map((entry: Record<string, unknown>) => ({
        id: asOptionalString(entry.id)?.trim() || '',
        name: asOptionalString(entry.name)?.trim() || '',
        prompt: asOptionalString(entry.prompt)?.trim() || '',
        checkpoint: asOptionalString(entry.checkpoint)?.trim() || '',
        loras: Array.isArray(entry.loras)
          ? entry.loras
              .filter((lora: unknown): lora is Record<string, unknown> => Boolean(lora && typeof lora === 'object'))
              .map((lora: Record<string, unknown>) => ({
                name: asOptionalString(lora.name)?.trim() || '',
                strength: Number.isFinite(Number(lora.strength)) ? Number(lora.strength) : 1,
              }))
          : [],
        thumbnailDataUrl: asOptionalString(entry.thumbnailDataUrl)?.trim() || undefined,
      }));
    const artStylePresets = await updateStudioArtStylePresets(presets);
    response.json({ artStylePresets });
  } catch (error) {
    response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to update artstyle presets.',
    });
  }
});

router.get('/automatic-generation/example-config', async (_request, response) => {
  try {
    const raw = await readFile(appConfig.exampleAutogenConfigPath, 'utf8');
    const parsed = JSON.parse(raw) as unknown;
    return response.json(parsed);
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to load example automatic generation config.',
    });
  }
});

router.post(
  '/assets/upload',
  express.raw({
    type: '*/*',
    limit: Number.MAX_SAFE_INTEGER,
  }),
  async (request, response) => {
    const ownerType = asOptionalString(request.query.ownerType)?.trim();
    const ownerId = asOptionalString(request.query.ownerId)?.trim();
    const relativePath = asOptionalString(request.query.path)
      ?.split('/')
      .map((part) => part.trim())
      .filter(Boolean);
    const fileStem = asOptionalString(request.query.name)?.trim();
    const body = Buffer.isBuffer(request.body) ? request.body : null;
    const mimeType = request.headers['content-type'] || '';

    if (
      (ownerType !== 'character' && ownerType !== 'scenario') ||
      !ownerId ||
      !relativePath ||
      relativePath.length === 0 ||
      !fileStem ||
      !body ||
      body.length === 0
    ) {
      return response.status(400).json({ error: 'Invalid asset upload.' });
    }

    try {
      const assetUrl = await saveUploadedStudioAsset({
        ownerType,
        ownerId,
        relativePath,
        fileStem,
        mimeType: Array.isArray(mimeType) ? mimeType[0] || '' : mimeType,
        data: body,
      });
      return response.json({ assetUrl });
    } catch (error) {
      return response.status(400).json({
        error: error instanceof Error ? error.message : 'Failed to upload asset.',
      });
    }
  },
);

router.post('/assets/delete-generated', async (request, response) => {
  const body =
    request.body && typeof request.body === 'object' && !Array.isArray(request.body)
      ? (request.body as Record<string, unknown>)
      : null;
  const filePathsRaw = Array.isArray(body?.filePaths) ? body.filePaths : [];
  const resolvedPaths = Array.from(
    new Set(
      filePathsRaw
        .map((value) => (typeof value === 'string' ? resolveGeneratedAssetPathForDeletion(value) : null))
        .filter((value): value is string => Boolean(value)),
    ),
  );

  if (filePathsRaw.length === 0) {
    return response.status(400).json({ error: 'No generated files were provided.' });
  }

  if (resolvedPaths.length === 0) {
    return response.status(400).json({ error: 'No valid generated files were provided.' });
  }

  try {
    await Promise.all(
      resolvedPaths.map(async (filePath) => {
        await rm(filePath, { force: true });
      }),
    );
    return response.json({ ok: true, deletedCount: resolvedPaths.length });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to delete generated asset files.',
    });
  }
});

router.get('/comfy/status', async (_request, response) => {
  try {
    const status = await getComfyStatus();
    return response.json(status);
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to check ComfyUI status.',
    });
  }
});

router.put('/comfy/connection', async (request, response) => {
  const body = request.body as Record<string, unknown> | null;
  const requestedBaseUrl = typeof body?.baseUrl === 'string' ? body.baseUrl : '';

  let normalizedBaseUrl = '';
  try {
    normalizedBaseUrl = normalizeComfyBaseUrl(requestedBaseUrl);
  } catch (error) {
    return response.status(400).json({
      error: error instanceof Error ? error.message : 'Invalid ComfyUI API address.',
    });
  }

  const previousBaseUrl = getComfyBaseUrl();
  setComfyBaseUrl(normalizedBaseUrl, { persist: false });

  try {
    const status = await getComfyStatus();
    if (!status.online) {
      throw new Error(status.error || 'ComfyUI is unreachable.');
    }

    setComfyBaseUrl(normalizedBaseUrl);
    return response.json({
      baseUrl: normalizedBaseUrl,
      online: true,
    });
  } catch (error) {
    setComfyBaseUrl(previousBaseUrl, { persist: false });
    return response.status(502).json({
      baseUrl: previousBaseUrl,
      online: false,
      error: error instanceof Error ? error.message : 'Failed to connect to ComfyUI.',
    });
  }
});

router.get('/comfy/options', async (_request, response) => {
  try {
    const options = await getComfyGenerationOptions();
    return response.json(options);
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to load ComfyUI options.',
    });
  }
});

router.post('/comfy/generate', async (request, response) => {
  const parsed = parseComfyGenerationPayload(request.body);
  if (!parsed) {
    return response.status(400).json({ error: 'Invalid generation payload.' });
  }

  try {
    const generated = await generateComfyImageAndSave(parsed);
    return response.json({ image: generated });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'ComfyUI generation failed.';
    const statusCode = /unavailable|unreachable|offline/i.test(message) ? 503 : 500;
    return response.status(statusCode).json({
      error: message,
    });
  }
});

router.post('/comfy/depth-map', async (request, response) => {
  const parsed = parseComfyDepthMapPayload(request.body);
  if (!parsed) {
    return response.status(400).json({ error: 'Invalid depth map payload.' });
  }

  try {
    const generated = await generateComfyDepthMapAndSave(parsed);
    return response.json({ image: generated });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'ComfyUI depth map generation failed.';
    const statusCode = /unavailable|unreachable|offline/i.test(message) ? 503 : 500;
    return response.status(statusCode).json({
      error: message,
    });
  }
});

router.post('/characters', async (request, response) => {
  const parsed = parseCharacterPayload(request.body);
  if (!parsed) {
    return response.status(400).json({ error: 'Invalid character payload.' });
  }

  try {
    const resolved = await resolveRetainedCharacterAssets(parsed);
    if (!resolved) {
      return response.status(400).json({ error: 'Invalid retained character assets.' });
    }
    const saved = await upsertStudioCharacter(resolved);
    return response.json({ character: shouldUseCompactCharacterResponse(request) ? toCompactCharacterResponse(saved) : saved });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to save character.',
    });
  }
});

router.put('/characters/:id', async (request, response) => {
  const parsed = parseCharacterPayload({
    ...request.body,
    id: request.params.id,
  });

  if (!parsed) {
    return response.status(400).json({ error: 'Invalid character payload.' });
  }

  try {
    const resolved = await resolveRetainedCharacterAssets(parsed);
    if (!resolved) {
      return response.status(400).json({ error: 'Invalid retained character assets.' });
    }
    const saved = await upsertStudioCharacter(resolved);
    return response.json({ character: shouldUseCompactCharacterResponse(request) ? toCompactCharacterResponse(saved) : saved });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to update character.',
    });
  }
});

router.delete('/characters/:id', async (request, response) => {
  try {
    const state = await getStudioState();
    const scenarioUsingCharacter = state.scenarios.find((scenario) => scenario.characterId === request.params.id);
    if (scenarioUsingCharacter) {
      return response.status(409).json({
        error: `Character is used by scenario "${scenarioUsingCharacter.name}". Delete or edit that scenario first.`,
      });
    }

    await deleteStudioCharacter(request.params.id);
    return response.json({ ok: true });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to delete character.',
    });
  }
});

router.post('/scenarios', async (request, response) => {
  const parsed = parseScenarioPayload(request.body);
  if (!parsed) {
    return response.status(400).json({ error: 'Invalid scenario payload.' });
  }

  try {
    const state = await getStudioState();
    if (!state.characters.some((entry) => entry.id === parsed.characterId)) {
      return response.status(400).json({ error: 'Selected character does not exist.' });
    }

    const saved = await upsertScenario(parsed);
    return response.json({ scenario: saved });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to save scenario.',
    });
  }
});

router.put('/scenarios/:id', async (request, response) => {
  const parsed = parseScenarioPayload({
    ...request.body,
    id: request.params.id,
  });

  if (!parsed) {
    return response.status(400).json({ error: 'Invalid scenario payload.' });
  }

  try {
    const state = await getStudioState();
    if (!state.characters.some((entry) => entry.id === parsed.characterId)) {
      return response.status(400).json({ error: 'Selected character does not exist.' });
    }

    const saved = await upsertScenario(parsed);
    return response.json({ scenario: saved });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to update scenario.',
    });
  }
});

router.delete('/scenarios/:id', async (request, response) => {
  try {
    await deleteScenario(request.params.id);
    return response.json({ ok: true });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to delete scenario.',
    });
  }
});

router.post('/runs', async (request, response) => {
  const parsed = parseRunCreatePayload(request.body);
  if (!parsed) {
    return response.status(400).json({ error: 'Invalid run payload.' });
  }

  try {
    const state = await getStudioState();
    if (!state.scenarios.some((entry) => entry.id === parsed.scenarioId)) {
      return response.status(400).json({ error: 'Selected scenario does not exist.' });
    }

    const saved = await createRun(parsed);
    return response.json({ run: saved });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to create run.',
    });
  }
});

router.put('/runs/:id/messages', async (request, response) => {
  const body = request.body as Record<string, unknown> | null;
  const messages = parseMessagesArray(body?.messages);
  if (!messages) {
    return response.status(400).json({ error: 'Invalid run messages payload.' });
  }
  const currentSceneId = asOptionalString(body?.currentSceneId)?.trim() || undefined;

  try {
    const saved = await updateRunMessages(request.params.id, messages, { currentSceneId });
    if (!saved) {
      return response.status(404).json({ error: 'Run not found.' });
    }
    return response.json({ run: saved });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to update run messages.',
    });
  }
});

router.delete('/runs/:id', async (request, response) => {
  try {
    await deleteRun(request.params.id);
    return response.json({ ok: true });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to delete run.',
    });
  }
});

router.post('/packages', async (request, response) => {
  const scenarioId = asOptionalString((request.body as Record<string, unknown> | null)?.scenarioId)?.trim();
  if (!scenarioId) {
    return response.status(400).json({ error: 'Scenario is required.' });
  }

  const requestedPackageName =
    asOptionalString((request.body as Record<string, unknown> | null)?.packageName)?.trim() || '';

  try {
    const state = await getStudioState();
    const scenario = state.scenarios.find((entry) => entry.id === scenarioId);
    if (!scenario) {
      return response.status(404).json({ error: 'Scenario not found.' });
    }

    const character = state.characters.find((entry) => entry.id === scenario.characterId);
    if (!character) {
      return response.status(404).json({ error: 'Scenario character not found.' });
    }

    await mkdir(appConfig.packageOutputPath, { recursive: true });
    const packageName = requestedPackageName || `${scenario.name} Package`;
    const fileName = `${slugifyFileName(packageName)}-${Date.now()}.zip`;
    const filePath = path.join(appConfig.packageOutputPath, fileName);
    const characterDirectory = path.join(appConfig.fileCharactersPath, path.basename(character.id));
    const scenarioDirectory = path.join(appConfig.fileScenesPath, path.basename(scenario.id));

    if (!isPathInsideDirectory(characterDirectory, appConfig.fileCharactersPath)) {
      return response.status(400).json({ error: 'Character folder path is invalid.' });
    }
    if (!isPathInsideDirectory(scenarioDirectory, appConfig.fileScenesPath)) {
      return response.status(400).json({ error: 'Scenario folder path is invalid.' });
    }

    const packageMetadata = {
      format: 'pettangatari-package',
      archiveFormat: 'folders-zip',
      version: 4,
      packageName,
      exportedAt: new Date().toISOString(),
      characterId: character.id,
      scenarioId: scenario.id,
      sillyTavernCharacterCardName: character.cardName,
      packageBannerDataUrl: scenario.bannerDataUrl || '',
    };

    const archive = new JSZip();
    const sillyTavernCard = await findSillyTavernCardForStudioCharacter(character);
    archive.file(PACKAGE_METADATA_FILE, `${JSON.stringify(packageMetadata, null, 2)}\n`);
    archive.file(SILLY_TAVERN_CHARACTER_CARD_FILE, `${JSON.stringify(sillyTavernCard, null, 2)}\n`);
    await addDirectoryToZip(archive, characterDirectory, `characters/${character.id}`);
    await addDirectoryToZip(archive, scenarioDirectory, `scenes/${scenario.id}`);
    const archiveBuffer = await archive.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    });
    await writeFile(filePath, archiveBuffer);

    const packageRecord = await addPackageRecord({
      name: packageName,
      bannerDataUrl: scenario.bannerDataUrl || '',
      scenarioId: scenario.id,
      characterId: character.id,
      fileName,
      filePath,
      source: 'created',
    });

    return response.json({ package: packageRecord });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to create package.',
    });
  }
});

router.post('/packages/import', async (request, response) => {
  const body = request.body as Record<string, unknown> | null;
  const fileName = asOptionalString(body?.fileName)?.trim() || `package-${Date.now()}.zip`;
  const packageData = asOptionalString(body?.packageData)?.trim() || '';
  const packageBuffer = parsePackageZipData(packageData);
  if (!packageBuffer) {
    return response.status(400).json({ error: 'Valid package ZIP is required.' });
  }

  try {
    let archive: JSZip;
    try {
      archive = await JSZip.loadAsync(packageBuffer);
    } catch {
      return response.status(400).json({ error: 'Package ZIP could not be read.' });
    }
    const metadata = await readPackageMetadata(archive);
    const extractionPlan = buildPackageExtractionPlan(archive);
    if (!extractionPlan) {
      return response.status(400).json({ error: 'Package ZIP must contain one character folder and one scenario folder.' });
    }
    try {
      await validatePackageManifests(extractionPlan);
    } catch (error) {
      return response.status(400).json({
        error: error instanceof Error ? error.message : 'Package manifests are invalid.',
      });
    }
    const sillyTavernCard = await readPackageSillyTavernCharacterCard(archive);

    await mkdir(appConfig.packageOutputPath, { recursive: true });
    const storedFileName = `${slugifyFileName(metadata.packageName || fileName.replace(/\.zip$/i, ''))}-${Date.now()}.zip`;
    const storedFilePath = path.join(appConfig.packageOutputPath, storedFileName);
    await writeFile(storedFilePath, packageBuffer);

    if (sillyTavernCard) {
      await importSillyTavernCharacterCard(sillyTavernCard);
    }

    await extractPackageFolders(extractionPlan);
    const importedState = await getStudioState();
    const character = importedState.characters.find((entry) => entry.id === extractionPlan.characterId);
    const scenario = importedState.scenarios.find((entry) => entry.id === extractionPlan.scenarioId);
    if (!character || !scenario) {
      return response.status(400).json({ error: 'Imported package folders did not contain valid manifests.' });
    }

    const packageRecord = await addPackageRecord({
      name: metadata.packageName || `${scenario.name} Package`,
      bannerDataUrl: scenario.bannerDataUrl || metadata.packageBannerDataUrl || '',
      scenarioId: scenario.id,
      characterId: character.id,
      fileName: storedFileName,
      filePath: storedFilePath,
      source: 'imported',
    });

    return response.json({
      package: packageRecord,
      character,
      scenario,
    });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to import package.',
    });
  }
});

router.post('/packages/:id/show-in-explorer', async (request, response) => {
  try {
    const state = await getStudioState();
    const packageRecord = state.packages.find((entry) => entry.id === request.params.id);
    if (!packageRecord) {
      return response.status(404).json({ error: 'Package not found.' });
    }

    const safePackageFilePath = resolvePackageFilePath(packageRecord.fileName, packageRecord.filePath);
    const explorer = spawn('explorer.exe', ['/select,', safePackageFilePath], {
      detached: true,
      stdio: 'ignore',
    });
    explorer.unref();
    return response.json({ ok: true });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to open Explorer.',
    });
  }
});

router.delete('/packages/:id', async (request, response) => {
  try {
    const body = request.body as Record<string, unknown> | null;
    const deleted = await deletePackageAndLinkedContent(request.params.id, {
      deleteCharacters: body?.deleteCharacters !== false,
      deleteScenarios: body?.deleteScenarios !== false,
    });
    if (deleted.deletedPackages.length === 0) {
      return response.status(404).json({ error: 'Package not found.' });
    }

    await Promise.all(
      deleted.deletedPackages.map(async (entry) => {
        const safePackageFilePath = resolvePackageFilePath(entry.fileName, entry.filePath);
        try {
          await rm(safePackageFilePath, { force: true });
        } catch {
          // noop
        }
      }),
    );

    return response.json({
      ok: true,
      deletedPackageIds: deleted.deletedPackages.map((entry) => entry.id),
      deletedScenarioIds: deleted.deletedScenarioIds,
      deletedCharacterIds: deleted.deletedCharacterIds,
    });
  } catch (error) {
    return response.status(500).json({
      error: error instanceof Error ? error.message : 'Failed to delete package.',
    });
  }
});

function asOptionalString(value: unknown): string | undefined {
  return typeof value === 'string' ? value : undefined;
}

function normalizeCardNameForMatch(value: unknown): string {
  return asOptionalString(value)?.trim().toLowerCase().replace(/\s+/g, ' ') || '';
}

function getSillyTavernCardDisplayName(card: SillyTavernCharacter): string {
  return (
    asOptionalString(card.data?.name)?.trim() ||
    asOptionalString(card.name)?.trim() ||
    ''
  );
}

function isSillyTavernCardMatch(card: SillyTavernCharacter, targetName: string): boolean {
  const normalizedTargetName = normalizeCardNameForMatch(targetName);
  if (!normalizedTargetName) {
    return false;
  }

  return [
    card.name,
    card.avatar,
    card.data?.name,
  ].some((candidate) => normalizeCardNameForMatch(candidate) === normalizedTargetName);
}

async function findSillyTavernCardForStudioCharacter(character: StudioCharacterRecord): Promise<SillyTavernCharacter> {
  let cards: SillyTavernCharacter[];
  try {
    cards = await sillyTavernClient.getCharacters();
  } catch (error) {
    throw new Error(
      `Could not export SillyTavern card "${character.cardName}". Make sure SillyTavern is running and connected. ${
        error instanceof Error ? error.message : ''
      }`.trim(),
    );
  }

  const card =
    cards.find((entry) => isSillyTavernCardMatch(entry, character.cardName)) ||
    cards.find((entry) => isSillyTavernCardMatch(entry, character.name));

  if (!card) {
    throw new Error(`Could not export SillyTavern card "${character.cardName}" for "${character.name}".`);
  }

  return card;
}

async function importSillyTavernCharacterCard(card: SillyTavernCharacter): Promise<void> {
  const cardName = getSillyTavernCardDisplayName(card);
  if (!cardName) {
    throw new Error('Package SillyTavern character card is missing a name.');
  }

  try {
    const existingCards = await sillyTavernClient.getCharacters();
    if (existingCards.some((entry) => isSillyTavernCardMatch(entry, cardName))) {
      return;
    }

    await sillyTavernClient.createCharacterFromCard(card);
  } catch (error) {
    throw new Error(
      `Could not import SillyTavern card "${cardName}". Make sure SillyTavern is running and connected. ${
        error instanceof Error ? error.message : ''
      }`.trim(),
    );
  }
}

function parseSceneWeatherPreset(value: unknown): SceneWeatherPreset {
  const normalized = asOptionalString(value)?.trim().toLowerCase() || '';
  return SCENE_WEATHER_PRESETS.has(normalized as SceneWeatherPreset) ? (normalized as SceneWeatherPreset) : 'none';
}

function isPathInsideDirectory(targetPath: string, directoryPath: string): boolean {
  const resolvedTarget = path.resolve(targetPath);
  const resolvedDirectory = path.resolve(directoryPath);
  const relative = path.relative(resolvedDirectory, resolvedTarget);
  return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative));
}

function resolvePackageFilePath(fileName: string, storedFilePath: string): string {
  const normalizedFileName = path.basename(fileName || '').trim();
  const preferredPath = path.resolve(appConfig.packageOutputPath, normalizedFileName);

  const normalizedStoredPath = asOptionalString(storedFilePath)?.trim() || '';
  if (!normalizedStoredPath) {
    return preferredPath;
  }

  const resolvedStoredPath = path.resolve(normalizedStoredPath);
  if (
    isPathInsideDirectory(resolvedStoredPath, appConfig.packageOutputPath) &&
    path.basename(resolvedStoredPath).toLowerCase() === normalizedFileName.toLowerCase()
  ) {
    return resolvedStoredPath;
  }

  return preferredPath;
}

async function addDirectoryToZip(archive: JSZip, sourceDirectory: string, archiveDirectory: string): Promise<void> {
  const entries = await readdir(sourceDirectory, { withFileTypes: true });
  for (const entry of entries) {
    const sourcePath = path.join(sourceDirectory, entry.name);
    const archivePath = `${archiveDirectory}/${entry.name}`.replace(/\\/g, '/');
    if (shouldSkipPackageArchiveEntry(archivePath, entry)) {
      continue;
    }
    if (entry.isDirectory()) {
      await addDirectoryToZip(archive, sourcePath, archivePath);
      continue;
    }
    if (!entry.isFile()) {
      continue;
    }

    archive.file(archivePath, await readFile(sourcePath));
  }
}

function shouldSkipPackageArchiveEntry(archivePath: string, entry: { isDirectory: () => boolean }): boolean {
  return entry.isDirectory() && /^characters\/[^/]+\/sprites\/cg-[^/]+$/i.test(archivePath);
}

function parsePackageZipData(value: string): Buffer | null {
  if (!value) {
    return null;
  }

  const match = value.match(/^data:[^;]+;base64,(.+)$/i);
  const base64 = match ? match[1] : value;
  if (!base64) {
    return null;
  }

  try {
    const buffer = Buffer.from(base64, 'base64');
    return buffer.length > 0 ? buffer : null;
  } catch {
    return null;
  }
}

type PackageZipMetadata = {
  packageName: string;
  packageBannerDataUrl: string;
};

async function readPackageMetadata(archive: JSZip): Promise<PackageZipMetadata> {
  const metadataFile = archive.file(PACKAGE_METADATA_FILE) || archive.file(LEGACY_PACKAGE_METADATA_FILE);
  if (!metadataFile) {
    return { packageName: '', packageBannerDataUrl: '' };
  }

  try {
    const metadata = JSON.parse(await metadataFile.async('string')) as Record<string, unknown>;
    return {
      packageName: asOptionalString(metadata.packageName)?.trim() || '',
      packageBannerDataUrl: asOptionalString(metadata.packageBannerDataUrl)?.trim() || '',
    };
  } catch {
    return { packageName: '', packageBannerDataUrl: '' };
  }
}

async function readPackageSillyTavernCharacterCard(archive: JSZip): Promise<SillyTavernCharacter | null> {
  const cardFile = archive.file(SILLY_TAVERN_CHARACTER_CARD_FILE);
  if (!cardFile) {
    return null;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(await cardFile.async('string'));
  } catch {
    throw new Error('Package SillyTavern character card could not be read.');
  }

  if (!parsed || typeof parsed !== 'object') {
    throw new Error('Package SillyTavern character card is invalid.');
  }

  const card = parsed as SillyTavernCharacter;
  const cardName = getSillyTavernCardDisplayName(card);
  if (!cardName) {
    throw new Error('Package SillyTavern character card is missing a name.');
  }

  return card;
}

type PackageExtractionPlan = {
  characterId: string;
  scenarioId: string;
  characterManifestFile: JSZip.JSZipObject;
  scenarioManifestFile: JSZip.JSZipObject;
  entries: Array<{
    file: JSZip.JSZipObject;
    relativePath: string;
  }>;
};

function normalizePackageArchivePath(value: string): string[] | null {
  const normalized = value.replace(/\\/g, '/').replace(/^\/+/, '');
  const parts = normalized.split('/').filter(Boolean);
  if (parts[0] === 'data') {
    parts.shift();
  }
  if (parts.some((part) => part === '.' || part === '..')) {
    return null;
  }
  return parts;
}

function buildPackageExtractionPlan(archive: JSZip): PackageExtractionPlan | null {
  const characterIds = new Set<string>();
  const scenarioIds = new Set<string>();
  const entries: PackageExtractionPlan['entries'] = [];
  let characterManifestFile: JSZip.JSZipObject | null = null;
  let scenarioManifestFile: JSZip.JSZipObject | null = null;

  for (const file of Object.values(archive.files)) {
    if (file.dir) {
      continue;
    }

    const parts = normalizePackageArchivePath(file.name);
    if (!parts || parts.length === 0) {
      return null;
    }

    const firstPart = parts[0];
    if (
      firstPart === PACKAGE_METADATA_FILE ||
      firstPart === LEGACY_PACKAGE_METADATA_FILE ||
      firstPart === '__MACOSX' ||
      firstPart === '.DS_Store'
    ) {
      continue;
    }

    if (firstPart === 'sillytavern') {
      if (parts.join('/') !== SILLY_TAVERN_CHARACTER_CARD_FILE) {
        return null;
      }
      continue;
    }

    if ((firstPart !== 'characters' && firstPart !== 'scenes') || parts.length < 3) {
      return null;
    }

    const folderId = parts[1];
    if (!folderId || folderId !== path.basename(folderId)) {
      return null;
    }

    if (firstPart === 'characters') {
      characterIds.add(folderId);
      if (parts[2] === CHARACTER_MANIFEST_FILE) {
        characterIds.add(folderId);
        characterManifestFile = file;
      }
    } else {
      scenarioIds.add(folderId);
      if (parts[2] === SCENARIO_MANIFEST_FILE) {
        scenarioIds.add(folderId);
        scenarioManifestFile = file;
      }
    }

    entries.push({
      file,
      relativePath: parts.join('/'),
    });
  }

  if (characterIds.size !== 1 || scenarioIds.size !== 1 || entries.length === 0 || !characterManifestFile || !scenarioManifestFile) {
    return null;
  }

  return {
    characterId: [...characterIds][0],
    scenarioId: [...scenarioIds][0],
    characterManifestFile,
    scenarioManifestFile,
    entries,
  };
}

async function validatePackageManifests(plan: PackageExtractionPlan): Promise<void> {
  const characterManifest = JSON.parse(await plan.characterManifestFile.async('string')) as Record<string, unknown>;
  const scenarioManifest = JSON.parse(await plan.scenarioManifestFile.async('string')) as Record<string, unknown>;

  if (asOptionalString(characterManifest.id) !== plan.characterId || !asOptionalString(characterManifest.name)?.trim()) {
    throw new Error('Package character manifest is invalid.');
  }

  if (
    asOptionalString(scenarioManifest.id) !== plan.scenarioId ||
    asOptionalString(scenarioManifest.characterId) !== plan.characterId ||
    !asOptionalString(scenarioManifest.name)?.trim()
  ) {
    throw new Error('Package scenario manifest is invalid.');
  }
}

async function extractPackageFolders(plan: PackageExtractionPlan): Promise<void> {
  const characterRoot = path.resolve(appConfig.fileCharactersPath, plan.characterId);
  const scenarioRoot = path.resolve(appConfig.fileScenesPath, plan.scenarioId);
  if (!isPathInsideDirectory(characterRoot, appConfig.fileCharactersPath)) {
    throw new Error('Package character folder path is invalid.');
  }
  if (!isPathInsideDirectory(scenarioRoot, appConfig.fileScenesPath)) {
    throw new Error('Package scenario folder path is invalid.');
  }

  await rm(characterRoot, { recursive: true, force: true });
  await rm(scenarioRoot, { recursive: true, force: true });

  for (const entry of plan.entries) {
    const targetPath = path.resolve(appConfig.rootDataPath, entry.relativePath);
    if (!isPathInsideDirectory(targetPath, appConfig.rootDataPath)) {
      throw new Error('Package contains an invalid file path.');
    }

    await mkdir(path.dirname(targetPath), { recursive: true });
    await writeFile(targetPath, await entry.file.async('nodebuffer'));
  }
}

function isImageDataUrl(value: string): boolean {
  return /^data:image\/[a-zA-Z0-9.+-]+;base64,/.test(value);
}

function isAudioDataUrl(value: string): boolean {
  return /^data:audio\/[a-zA-Z0-9.+-]+;base64,/.test(value);
}

function isStoredAssetUrl(value: string): boolean {
  return value.startsWith('/api/studio/assets/');
}

function isImageAssetReference(value: string): boolean {
  return isImageDataUrl(value) || isStoredAssetUrl(value);
}

function isAudioAssetReference(value: string): boolean {
  return isAudioDataUrl(value) || isStoredAssetUrl(value);
}

function isRetainedCharacterAssetToken(value: string): boolean {
  return value === KEEP_CHARACTER_ASSET_TOKEN || value === LEGACY_KEEP_CHARACTER_ASSET_TOKEN;
}

function parseImageVariants(value: unknown): string[] | null {
  const rawValues = Array.isArray(value) ? value : typeof value === 'string' ? [value] : [];
  const variants = rawValues
    .map((entry) => asOptionalString(entry)?.trim() || '')
    .filter(Boolean)
    .slice(0, MAX_ASSET_VARIANTS);

  if (variants.some((entry) => !isImageAssetReference(entry) && !isRetainedCharacterAssetToken(entry))) {
    return null;
  }

  return variants;
}

function parseSpriteAnimationFrames(value: unknown, spriteCount: number): { closedEyes: string[]; openMouth: string[] } | null {
  const record = value && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
  const closedEyes = parseImageVariants(record.closedEyes);
  const openMouth = parseImageVariants(record.openMouth);
  if (!closedEyes || !openMouth) {
    return null;
  }

  return {
    closedEyes: closedEyes.slice(0, spriteCount),
    openMouth: openMouth.slice(0, spriteCount),
  };
}

function parseAccentColor(value: unknown): string | null {
  if (typeof value !== 'string') {
    return null;
  }

  const trimmed = value.trim();
  if (!/^#[0-9a-fA-F]{6}$/.test(trimmed)) {
    return null;
  }

  return trimmed.toLowerCase();
}

function normalizeReactionName(value: string): string {
  return value
    .replace(/[\[\]]/g, ' ')
    .trim()
    .replace(/\s+/g, ' ')
    .toUpperCase();
}

function parseTriggerWords(value: unknown): string[] {
  const values = typeof value === 'string' ? value.split(',') : Array.isArray(value) ? value : [];
  const seen = new Set<string>();
  const triggerWords: string[] = [];

  for (const entry of values) {
    if (typeof entry !== 'string') {
      continue;
    }

    const next = entry.trim();
    if (!next) {
      continue;
    }

    const key = next.toLowerCase();
    if (seen.has(key)) {
      continue;
    }

    seen.add(key);
    triggerWords.push(next);
  }

  return triggerWords;
}

function parseMessagesArray(value: unknown): ScenarioRunMessage[] | null {
  if (!Array.isArray(value)) {
    return null;
  }

  const messages: ScenarioRunMessage[] = [];
  for (const entry of value) {
    if (!entry || typeof entry !== 'object') {
      continue;
    }

    const role = (entry as Record<string, unknown>).role;
    const content = (entry as Record<string, unknown>).content;
    if ((role === 'user' || role === 'assistant') && typeof content === 'string') {
      messages.push({ role, content });
    }
  }

  return messages;
}

function parseAutomaticGenerationSettings(value: unknown): CharacterAutomaticGenerationRecord {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return {
      ...DEFAULT_CHARACTER_AUTOMATIC_GENERATION,
      loras: [],
      customExpressions: [],
      cgDefinitions: [],
    };
  }

  const record = value as Record<string, unknown>;
  const lorasRaw = Array.isArray(record.loras) ? record.loras : [];
  const customExpressionsRaw = Array.isArray(record.customExpressions) ? record.customExpressions : [];
  const cgDefinitionsRaw = Array.isArray(record.cgDefinitions) ? record.cgDefinitions : [];
  const defaultExpressionsRaw = Array.isArray(record.defaultExpressions) ? record.defaultExpressions : [];
  const artStylePresetsRaw = Array.isArray(record.artStylePresets) ? record.artStylePresets : [];

  const loras: CharacterAutomaticGenerationRecord['loras'] = lorasRaw
    .filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === 'object'))
    .map((entry) => ({
      name: asOptionalString(entry.name)?.trim() || '',
      strength: typeof entry.strength === 'number' && Number.isFinite(entry.strength) ? entry.strength : 1,
    }))
    .filter((entry) => entry.name)
    .map((entry) => ({
      ...entry,
      strength: Math.min(Math.max(entry.strength, -4), 4),
    }));

  const customExpressions: CharacterAutomaticGenerationRecord['customExpressions'] = customExpressionsRaw
    .filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === 'object'))
    .map((entry) => ({
      enabled: entry.enabled !== false,
      triggerTag: normalizeReactionName(asOptionalString(entry.triggerTag)?.trim() || ''),
      prompt: asOptionalString(entry.prompt)?.trim() || '',
    }))
      .filter((entry) => entry.triggerTag);

  const defaultExpressions: CharacterAutomaticGenerationRecord['defaultExpressions'] = defaultExpressionsRaw
    .filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === 'object'))
    .map((entry) => ({
      enabled: entry.enabled !== false,
      expression: normalizeReactionName(asOptionalString(entry.expression)?.trim() || ''),
      prompt: asOptionalString(entry.prompt)?.trim() || '',
    }))
    .filter((entry) => entry.expression);

  const cgDefinitions: CharacterAutomaticGenerationRecord['cgDefinitions'] = cgDefinitionsRaw
    .filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === 'object'))
    .map((entry) => ({
      enabled: entry.enabled !== false,
      triggerTag: normalizeReactionName(asOptionalString(entry.triggerTag)?.trim() || ''),
      prompt: asOptionalString(entry.prompt)?.trim() || '',
      excludeUpperBodyTags: entry.excludeUpperBodyTags === true,
      excludeWaistTags: entry.excludeWaistTags === true,
      excludeLowerBodyTags: entry.excludeLowerBodyTags === true,
    }))
    .filter((entry) => entry.triggerTag);
  const artStylePresets: CharacterAutomaticGenerationRecord['artStylePresets'] = artStylePresetsRaw
    .filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === 'object'))
    .map((entry, index) => ({
      id: asOptionalString(entry.id)?.trim() || `style-${index + 1}`,
      name: asOptionalString(entry.name)?.trim().slice(0, 60) || '',
      prompt: asOptionalString(entry.prompt)?.trim() || '',
      checkpoint: asOptionalString(entry.checkpoint)?.trim() || '',
      loras: (Array.isArray(entry.loras) ? entry.loras : [])
        .filter((lora): lora is Record<string, unknown> => Boolean(lora && typeof lora === 'object'))
        .map((lora) => ({
          name: asOptionalString(lora.name)?.trim() || '',
          strength:
            typeof lora.strength === 'number' && Number.isFinite(lora.strength)
              ? Math.min(Math.max(lora.strength, -4), 4)
              : 1,
        }))
        .filter((lora) => lora.name),
      thumbnailDataUrl:
        typeof entry.thumbnailDataUrl === 'string' && entry.thumbnailDataUrl.startsWith('data:image/')
          ? entry.thumbnailDataUrl
          : undefined,
    }))
    .filter((entry) => entry.name && entry.prompt);

  const expressionVariantCountRaw = record.expressionVariantCount;
  const expressionVariantCount =
    typeof expressionVariantCountRaw === 'number' && Number.isFinite(expressionVariantCountRaw)
      ? Math.min(Math.max(Math.round(expressionVariantCountRaw), 0), MAX_ASSET_VARIANTS)
      : DEFAULT_CHARACTER_AUTOMATIC_GENERATION.expressionVariantCount;
  const cgVariantCountRaw = record.cgVariantCount;
  const cgVariantCount =
    typeof cgVariantCountRaw === 'number' && Number.isFinite(cgVariantCountRaw)
      ? Math.min(Math.max(Math.round(cgVariantCountRaw), 0), MAX_ASSET_VARIANTS)
      : DEFAULT_CHARACTER_AUTOMATIC_GENERATION.cgVariantCount;
  const stepsRaw = record.steps;
  const steps =
    typeof stepsRaw === 'number' && Number.isFinite(stepsRaw)
      ? Math.min(Math.max(Math.round(stepsRaw), 1), 150)
      : DEFAULT_CHARACTER_AUTOMATIC_GENERATION.steps;
  const generatedPromptBySlotRaw =
    record.generatedPromptBySlot && typeof record.generatedPromptBySlot === 'object' && !Array.isArray(record.generatedPromptBySlot)
      ? (record.generatedPromptBySlot as Record<string, unknown>)
      : {};
  const generatedPromptBySlot = Object.fromEntries(
    Object.entries(generatedPromptBySlotRaw)
      .map(([slotKey, prompt]) => [slotKey.trim(), asOptionalString(prompt)?.trim() || ''] as const)
      .filter(([slotKey, prompt]) => slotKey && prompt),
  );
  const resumeStateRaw =
    record.resumeState && typeof record.resumeState === 'object' && !Array.isArray(record.resumeState)
      ? (record.resumeState as Record<string, unknown>)
      : null;
  const parsedResumeMode: 'replace' | 'append' | null =
    resumeStateRaw?.mode === 'replace' || resumeStateRaw?.mode === 'append' ? resumeStateRaw.mode : null;
  const appendBaseIndexByAsset =
    resumeStateRaw &&
    resumeStateRaw.appendBaseIndexByAsset &&
    typeof resumeStateRaw.appendBaseIndexByAsset === 'object' &&
    !Array.isArray(resumeStateRaw.appendBaseIndexByAsset)
      ? Object.fromEntries(
          Object.entries(resumeStateRaw.appendBaseIndexByAsset as Record<string, unknown>)
            .map(([assetKey, index]) => [
              assetKey.trim(),
              typeof index === 'number' && Number.isFinite(index) ? Math.max(0, Math.round(index)) : -1,
            ] as const)
            .filter(([assetKey, index]) => assetKey && index >= 0),
        )
      : {};
  const resumeState =
    resumeStateRaw &&
    parsedResumeMode &&
    typeof resumeStateRaw.nextTaskIndex === 'number' &&
    Number.isFinite(resumeStateRaw.nextTaskIndex) &&
    typeof resumeStateRaw.totalTasks === 'number' &&
    Number.isFinite(resumeStateRaw.totalTasks) &&
    typeof resumeStateRaw.taskSignature === 'string' &&
    resumeStateRaw.taskSignature.trim()
      ? {
          mode: parsedResumeMode,
          nextTaskIndex: Math.max(0, Math.round(resumeStateRaw.nextTaskIndex)),
          totalTasks: Math.max(0, Math.round(resumeStateRaw.totalTasks)),
          taskSignature: resumeStateRaw.taskSignature.trim(),
          appendBaseIndexByAsset,
          updatedAt: asOptionalString(resumeStateRaw.updatedAt)?.trim() || new Date().toISOString(),
        }
      : null;
  const normalizePreferredExpression = (
    value: unknown,
  ): CharacterAutomaticGenerationRecord['preferredCgExpression'] => {
    const normalized = asOptionalString(value)?.trim().toUpperCase() || '';
    return normalized === 'HAPPY' ||
      normalized === 'ANNOYED' ||
      normalized === 'EXPRESSIONLESS' ||
      normalized === 'CRYING' ||
      normalized === 'LIGHT_SMILE' ||
      normalized === 'NAUGHTY_FACE' ||
      normalized === 'AHEGAO'
      ? normalized
      : 'ANY';
  };
  const hasPreferredPenetrationExpression = Object.prototype.hasOwnProperty.call(record, 'preferredPenetrationExpression');
  const preferredPenetrationExpression = normalizePreferredExpression(
    hasPreferredPenetrationExpression ? record.preferredPenetrationExpression : record.preferredCgExpression,
  );
  const preferredCgExpression = hasPreferredPenetrationExpression
    ? normalizePreferredExpression(record.preferredCgExpression)
    : DEFAULT_CHARACTER_AUTOMATIC_GENERATION.preferredCgExpression;
  const lightingColorRaw = asOptionalString(record.lightingColor)?.trim().toUpperCase() || '';
  const lightingColor: CharacterAutomaticGenerationRecord['lightingColor'] =
    lightingColorRaw === 'BLUE' ||
    lightingColorRaw === 'RED' ||
    lightingColorRaw === 'PURPLE' ||
    lightingColorRaw === 'ORANGE' ||
    lightingColorRaw === 'YELLOW' ||
    lightingColorRaw === 'GREEN' ||
    lightingColorRaw === 'PINK'
      ? lightingColorRaw
      : 'NEUTRAL';
  const breastSizeRaw = asOptionalString(record.breastSize)?.trim().toUpperCase() || '';
  const breastSize: CharacterAutomaticGenerationRecord['breastSize'] =
    breastSizeRaw === 'FLAT' ||
    breastSizeRaw === 'SMALL' ||
    breastSizeRaw === 'LARGE' ||
    breastSizeRaw === 'HUGE' ||
    breastSizeRaw === 'GIGANTIC'
      ? breastSizeRaw
      : 'MEDIUM';
  const bloomIntensityRaw = record.bloomIntensity;
  const bloomIntensity =
    typeof bloomIntensityRaw === 'number' && Number.isFinite(bloomIntensityRaw)
      ? Math.min(Math.max(bloomIntensityRaw, 0), 1)
      : DEFAULT_CHARACTER_AUTOMATIC_GENERATION.bloomIntensity;
  const generateDepthMaps =
    typeof record.generateDepthMaps === 'boolean'
      ? record.generateDepthMaps
      : DEFAULT_CHARACTER_AUTOMATIC_GENERATION.generateDepthMaps;
  const generateMouthAnimations =
    typeof record.generateMouthAnimations === 'boolean'
      ? record.generateMouthAnimations
      : typeof record.generateBlinkingAndTalking === 'boolean'
        ? record.generateBlinkingAndTalking
        : DEFAULT_CHARACTER_AUTOMATIC_GENERATION.generateMouthAnimations;

  return {
    checkpoint: asOptionalString(record.checkpoint)?.trim() || '',
    upscaleModel: asOptionalString(record.upscaleModel)?.trim() || '',
    loras,
    basePrompt: asOptionalString(record.basePrompt)?.trim() || '',
    negativePrompt: asOptionalString(record.negativePrompt)?.trim() || '',
    artStylePrompt: asOptionalString(record.artStylePrompt)?.trim() || '',
    artStylePresets,
    characterMainTags: asOptionalString(record.characterMainTags)?.trim() || '',
    upperBodyTags: asOptionalString(record.upperBodyTags)?.trim() || '',
    waistTags: asOptionalString(record.waistTags)?.trim() || '',
    openMouthTags: asOptionalString(record.openMouthTags)?.trim() || '',
    lowerBodyTags: asOptionalString(record.lowerBodyTags)?.trim() || '',
    expressionVariantCount,
    cgVariantCount,
    steps,
    preferredPenetrationExpression,
    preferredCgExpression,
    lightingColor,
    breastSize,
    bloomIntensity,
    generateDepthMaps,
    generateMouthAnimations,
    defaultExpressions,
    customExpressions,
    cgDefinitions,
    generatedPromptBySlot,
    resumeState,
  };
}

function parseComfyGenerationPayload(body: unknown): {
  workflowKind: 'sprite' | 'cg';
  characterName: string;
  label: string;
  variantNumber: number;
  prompt: string;
  negativePrompt?: string;
  checkpoint: string;
  steps?: number;
  upscaleModel: string;
  loras: Array<{ name: string; strength: number }>;
  latentWidth?: number;
  latentHeight?: number;
  skipFaceDetailer?: boolean;
  skipBackgroundRemoval?: boolean;
  generateDepthMap?: boolean;
  generateAnimationFrames?: boolean;
  animationFramePrompts?: {
    closedEyes?: string;
    openMouth?: string;
  };
} | null {
  if (!body || typeof body !== 'object') {
    return null;
  }

  const record = body as Record<string, unknown>;
  const workflowKind = record.workflowKind === 'cg' ? 'cg' : record.workflowKind === 'sprite' ? 'sprite' : null;
  const characterName = asOptionalString(record.characterName)?.trim() || '';
  const label = asOptionalString(record.label)?.trim() || '';
  const prompt = asOptionalString(record.prompt)?.trim() || '';
  const negativePrompt = asOptionalString(record.negativePrompt)?.trim() || '';
  const checkpoint = asOptionalString(record.checkpoint)?.trim() || '';
  const upscaleModel = asOptionalString(record.upscaleModel)?.trim() || '';
  const steps =
    typeof record.steps === 'number' && Number.isFinite(record.steps)
      ? Math.min(Math.max(Math.round(record.steps), 1), 150)
      : 30;
  const variantNumber =
    typeof record.variantNumber === 'number' && Number.isFinite(record.variantNumber)
      ? Math.max(1, Math.round(record.variantNumber))
      : 1;
  const latentWidth =
    typeof record.latentWidth === 'number' && Number.isFinite(record.latentWidth)
      ? Math.max(64, Math.round(record.latentWidth))
      : undefined;
  const latentHeight =
    typeof record.latentHeight === 'number' && Number.isFinite(record.latentHeight)
      ? Math.max(64, Math.round(record.latentHeight))
      : undefined;
  const skipFaceDetailer = workflowKind === 'cg' || record.skipFaceDetailer === true;
  const skipBackgroundRemoval = record.skipBackgroundRemoval === true;
  const generateDepthMap = record.generateDepthMap === true;
  const generateAnimationFrames = workflowKind === 'sprite' && record.generateAnimationFrames === true;
  const animationFramePromptsRaw =
    record.animationFramePrompts && typeof record.animationFramePrompts === 'object' && !Array.isArray(record.animationFramePrompts)
      ? (record.animationFramePrompts as Record<string, unknown>)
      : {};
  const animationFramePrompts = {
    closedEyes: asOptionalString(animationFramePromptsRaw.closedEyes)?.trim() || undefined,
    openMouth: asOptionalString(animationFramePromptsRaw.openMouth)?.trim() || undefined,
  };

  if (!workflowKind || !characterName || !label || !prompt) {
    return null;
  }

  const lorasRaw = Array.isArray(record.loras) ? record.loras : [];
  const loras = lorasRaw
    .filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === 'object'))
    .map((entry) => ({
      name: asOptionalString(entry.name)?.trim() || '',
      strength: typeof entry.strength === 'number' && Number.isFinite(entry.strength) ? entry.strength : 1,
    }))
    .filter((entry) => entry.name)
    .map((entry) => ({
      name: entry.name,
      strength: Math.min(Math.max(entry.strength, -4), 4),
    }));

  return {
    workflowKind,
    characterName,
    label,
    variantNumber,
    prompt,
    negativePrompt,
    checkpoint,
    steps,
    upscaleModel,
    loras,
    latentWidth,
    latentHeight,
    skipFaceDetailer,
    skipBackgroundRemoval,
    generateDepthMap,
    generateAnimationFrames,
    animationFramePrompts,
  };
}

function parseComfyDepthMapPayload(body: unknown): {
  imageDataUrl: string;
  characterName: string;
  label: string;
  variantNumber: number;
} | null {
  if (!body || typeof body !== 'object') {
    return null;
  }

  const record = body as Record<string, unknown>;
  const imageDataUrl = asOptionalString(record.imageDataUrl)?.trim() || '';
  const characterName = asOptionalString(record.characterName)?.trim() || '';
  const label = asOptionalString(record.label)?.trim() || '';
  const variantNumber =
    typeof record.variantNumber === 'number' && Number.isFinite(record.variantNumber)
      ? Math.max(1, Math.round(record.variantNumber))
      : 1;

  if (!imageDataUrl || !isImageDataUrl(imageDataUrl) || !characterName || !label) {
    return null;
  }

  return {
    imageDataUrl,
    characterName,
    label,
    variantNumber,
  };
}

function parseCharacterPayload(
  body: unknown,
): {
  id?: string;
  name: string;
  cardName: string;
  accentColor: string;
  suggestedAffinityPositiveMaximum?: number;
  suggestedAffinityNegativeMaximum?: number;
  suggestedLustMaximum?: number;
  characterNameFontId?: string;
  characterNameColor?: string;
  blipSound?: string;
  dialogueQuoteFontId?: string;
  dialogueQuoteAnimationPreset?: string;
  dialogueQuoteAnimationSpeed?: number;
  dialogueQuoteAnimationColor?: string;
  sprites: Record<string, string[]>;
  spriteDepthMaps: Record<string, string[]>;
  spriteAnimationFrames: Record<string, { closedEyes: string[]; openMouth: string[] }>;
  customReactions: Array<{
    name: string;
    sprites: string[];
    depthMaps?: string[];
    animationFrames?: { closedEyes: string[]; openMouth: string[] };
    triggers: string[];
  }>;
  automaticGeneration: CharacterAutomaticGenerationRecord;
  spriteZones: Record<
    string,
    Array<{ id: string; x: number; y: number; width: number; height: number; prompt: string }>
  >;
  cgs: Array<{ name: string; images: string[]; triggers: string[] }>;
} | null {
  if (!body || typeof body !== 'object') {
    return null;
  }

  const record = body as Record<string, unknown>;
  const name = asOptionalString(record.name)?.trim();
  const cardName = asOptionalString(record.cardName)?.trim();
  const accentColor = parseAccentColor(record.accentColor);
  const id = asOptionalString(record.id)?.trim() || undefined;
  const suggestedAffinityPositiveMaximum =
    typeof record.suggestedAffinityPositiveMaximum === 'number' && Number.isFinite(record.suggestedAffinityPositiveMaximum)
      ? Math.min(Math.max(Math.round(record.suggestedAffinityPositiveMaximum), 0), 120)
      : undefined;
  const suggestedAffinityNegativeMaximum =
    typeof record.suggestedAffinityNegativeMaximum === 'number' && Number.isFinite(record.suggestedAffinityNegativeMaximum)
      ? Math.min(Math.max(Math.round(record.suggestedAffinityNegativeMaximum), -120), 0)
      : undefined;
  const suggestedLustMaximum =
    typeof record.suggestedLustMaximum === 'number' && Number.isFinite(record.suggestedLustMaximum)
      ? Math.min(Math.max(Math.round(record.suggestedLustMaximum), 0), 100)
      : undefined;
  const characterNameFontId = normalizeDialogueQuoteFontId(record.characterNameFontId);
  const blipSound = asOptionalString(record.blipSound)?.trim() || '';
  const dialogueQuoteFontId = normalizeDialogueQuoteFontId(record.dialogueQuoteFontId);
  const dialogueQuoteAnimationPreset = normalizeDialogueQuoteAnimationPreset(record.dialogueQuoteAnimationPreset);
  const dialogueQuoteAnimationSpeed = normalizeDialogueQuoteAnimationSpeed(record.dialogueQuoteAnimationSpeed);
  const dialogueQuoteAnimationColor = normalizeDialogueQuoteAnimationColor(record.dialogueQuoteAnimationColor);

  if (!name || !cardName || !accentColor) {
    return null;
  }
  const characterNameColor = parseAccentColor(record.characterNameColor) || accentColor;

  const spritesRaw = record.sprites;
  if (!spritesRaw || typeof spritesRaw !== 'object') {
    return null;
  }

  const sprites: Record<string, string[]> = {};
  for (const expression of SPRITE_EXPRESSIONS) {
    const variants = parseImageVariants((spritesRaw as Record<string, unknown>)[expression]);
    if (!variants) {
      return null;
    }

    if (variants.length === 0) {
      sprites[expression] = [];
      continue;
    }

    sprites[expression] = variants;
  }

  const spriteDepthMapsRaw =
    record.spriteDepthMaps && typeof record.spriteDepthMaps === 'object' && !Array.isArray(record.spriteDepthMaps)
      ? (record.spriteDepthMaps as Record<string, unknown>)
      : {};
  const spriteDepthMaps: Record<string, string[]> = {};
  for (const expression of SPRITE_EXPRESSIONS) {
    const depthVariants = parseImageVariants(spriteDepthMapsRaw[expression]);
    if (!depthVariants) {
      return null;
    }
    spriteDepthMaps[expression] = depthVariants.slice(0, sprites[expression].length);
  }

  const spriteAnimationFramesRaw =
    record.spriteAnimationFrames && typeof record.spriteAnimationFrames === 'object' && !Array.isArray(record.spriteAnimationFrames)
      ? (record.spriteAnimationFrames as Record<string, unknown>)
      : {};
  const spriteAnimationFrames: Record<string, { closedEyes: string[]; openMouth: string[] }> = {};
  for (const expression of SPRITE_EXPRESSIONS) {
    const frames = parseSpriteAnimationFrames(spriteAnimationFramesRaw[expression], sprites[expression].length);
    if (!frames) {
      return null;
    }
    spriteAnimationFrames[expression] = frames;
  }

  const customReactionsRaw = Array.isArray(record.customReactions) ? record.customReactions : [];
  const customReactions: Array<{
    name: string;
    sprites: string[];
    depthMaps?: string[];
    animationFrames?: { closedEyes: string[]; openMouth: string[] };
    triggers: string[];
  }> = [];
  const customReactionNames = new Set<string>();
  const automaticGeneration = parseAutomaticGenerationSettings(record.automaticGeneration);

  for (const entry of customReactionsRaw) {
    if (!entry || typeof entry !== 'object') {
      return null;
    }

    const item = entry as Record<string, unknown>;
    const normalizedTriggers = (Array.isArray(item.triggers) ? item.triggers : [item.name])
      .map((trigger) => normalizeReactionName(asOptionalString(trigger)?.trim() || ''))
      .filter(Boolean)
      .filter((trigger, index, list) => list.indexOf(trigger) === index);
    const normalizedName = normalizedTriggers[0] || '';
    const sprites = parseImageVariants(item.sprites ?? item.sprite);
    const depthMaps = parseImageVariants(item.depthMaps ?? item.depthMap);

    if (!normalizedName || !/^[A-Z0-9 _-]{1,40}$/.test(normalizedName)) {
      return null;
    }

    if (!sprites || sprites.length === 0 || !depthMaps) {
      return null;
    }

    const animationFrames = parseSpriteAnimationFrames(item.animationFrames, sprites.length);
    if (!animationFrames) {
      return null;
    }

    if (normalizedTriggers.some((trigger) => customReactionNames.has(trigger))) {
      return null;
    }

    normalizedTriggers.forEach((trigger) => customReactionNames.add(trigger));
    customReactions.push({
      name: normalizedName,
      sprites,
      depthMaps: depthMaps.slice(0, sprites.length),
      animationFrames:
        animationFrames.closedEyes.some(Boolean) || animationFrames.openMouth.some(Boolean)
          ? animationFrames
          : undefined,
      triggers: normalizedTriggers,
    });
  }

  const spriteZonesRaw =
    record.spriteZones && typeof record.spriteZones === 'object' && !Array.isArray(record.spriteZones)
      ? (record.spriteZones as Record<string, unknown>)
      : {};
  const spriteZones: Record<
    string,
    Array<{ id: string; x: number; y: number; width: number; height: number; prompt: string }>
  > = {};

  for (const [expressionKey, zoneValue] of Object.entries(spriteZonesRaw)) {
    const normalizedKey = normalizeReactionName(expressionKey);
    if (!normalizedKey || !Array.isArray(zoneValue)) {
      continue;
    }

    const zones: Array<{ id: string; x: number; y: number; width: number; height: number; prompt: string }> = [];

    for (const zoneEntry of zoneValue) {
      if (!zoneEntry || typeof zoneEntry !== 'object') {
        return null;
      }

      const zoneRecord = zoneEntry as Record<string, unknown>;
      const id = asOptionalString(zoneRecord.id)?.trim() || '';
      const prompt = asOptionalString(zoneRecord.prompt)?.trim() || '';
      const x = typeof zoneRecord.x === 'number' && Number.isFinite(zoneRecord.x) ? zoneRecord.x : NaN;
      const y = typeof zoneRecord.y === 'number' && Number.isFinite(zoneRecord.y) ? zoneRecord.y : NaN;
      const width = typeof zoneRecord.width === 'number' && Number.isFinite(zoneRecord.width) ? zoneRecord.width : NaN;
      const height = typeof zoneRecord.height === 'number' && Number.isFinite(zoneRecord.height) ? zoneRecord.height : NaN;

      if (
        !id ||
        Number.isNaN(x) ||
        Number.isNaN(y) ||
        Number.isNaN(width) ||
        Number.isNaN(height) ||
        x < 0 ||
        x > 1 ||
        y < 0 ||
        y > 1 ||
        width <= 0 ||
        width > 1 ||
        height <= 0 ||
        height > 1 ||
        x + width > 1.000001 ||
        y + height > 1.000001
      ) {
        return null;
      }

      zones.push({
        id,
        x,
        y,
        width,
        height,
        prompt,
      });
    }

    if (zones.length > 0) {
      spriteZones[normalizedKey] = zones;
    }
  }

  const cgsRaw = Array.isArray(record.cgs) ? record.cgs : [];
  const cgs: Array<{ name: string; images: string[]; triggers: string[] }> = [];
  const cgNames = new Set<string>();

  for (const entry of cgsRaw) {
    if (!entry || typeof entry !== 'object') {
      return null;
    }

    const item = entry as Record<string, unknown>;
    const triggers = (Array.isArray(item.triggers) ? item.triggers : [item.name])
      .map((trigger) => normalizeReactionName(asOptionalString(trigger)?.trim() || ''))
      .filter(Boolean)
      .filter((trigger, index, list) => list.indexOf(trigger) === index);
    const name = triggers[0] || '';
    const images = parseImageVariants(item.images ?? item.image);

    if (!name || !images || images.length === 0) {
      return null;
    }

    if (triggers.some((trigger) => cgNames.has(trigger.toLowerCase()))) {
      return null;
    }

    triggers.forEach((trigger) => cgNames.add(trigger.toLowerCase()));
    cgs.push({ name, images, triggers });
  }

  return {
    id,
    name,
    cardName,
    accentColor,
    suggestedAffinityPositiveMaximum,
    suggestedAffinityNegativeMaximum,
    suggestedLustMaximum,
    characterNameFontId: characterNameFontId || undefined,
    characterNameColor,
    blipSound: /^[a-zA-Z0-9._-]+$/.test(blipSound) ? blipSound : undefined,
    dialogueQuoteFontId: dialogueQuoteFontId || undefined,
    dialogueQuoteAnimationPreset,
    dialogueQuoteAnimationSpeed,
    dialogueQuoteAnimationColor,
    sprites,
    spriteDepthMaps,
    spriteAnimationFrames,
    customReactions,
    automaticGeneration,
    spriteZones,
    cgs,
  };
}

function normalizeDialogueQuoteFontId(value: unknown): string {
  const normalized = `${value || ''}`.trim().toLowerCase();
  return /^[a-z0-9-]{1,80}$/.test(normalized) ? normalized : '';
}

function normalizeDialogueQuoteAnimationPreset(value: unknown): string {
  const normalized = `${value || ''}`.trim().toLowerCase();
  return ['disabled', 'glowing', 'crawlies', 'wave', 'flicker', 'glitch', 'echo'].includes(normalized)
    ? normalized
    : 'disabled';
}

function normalizeDialogueQuoteAnimationSpeed(value: unknown): number {
  const numeric = typeof value === 'number' ? value : Number.parseFloat(`${value || ''}`);
  if (!Number.isFinite(numeric)) {
    return 1;
  }

  return Math.min(Math.max(numeric, 0.25), 3);
}

function normalizeDialogueQuoteAnimationColor(value: unknown): string {
  const parsed = parseAccentColor(value);
  return parsed ? parsed.toUpperCase() : '#F6F0E6';
}

type ParsedCharacterPayload = NonNullable<ReturnType<typeof parseCharacterPayload>>;

function hasRetainedCharacterAssets(payload: ParsedCharacterPayload): boolean {
  return (
    Object.values(payload.sprites).some((variants) => variants.some(isRetainedCharacterAssetToken)) ||
    Object.values(payload.spriteDepthMaps).some((variants) => variants.some(isRetainedCharacterAssetToken)) ||
    Object.values(payload.spriteAnimationFrames).some(
      (frames) =>
        frames.closedEyes.some(isRetainedCharacterAssetToken) ||
        frames.openMouth.some(isRetainedCharacterAssetToken),
    ) ||
    payload.customReactions.some(
      (reaction) =>
        reaction.sprites.some(isRetainedCharacterAssetToken) ||
        (reaction.depthMaps || []).some(isRetainedCharacterAssetToken) ||
        (reaction.animationFrames?.closedEyes || []).some(isRetainedCharacterAssetToken) ||
        (reaction.animationFrames?.openMouth || []).some(isRetainedCharacterAssetToken),
    ) ||
    payload.cgs.some((cg) => cg.images.some(isRetainedCharacterAssetToken))
  );
}

function resolveImageVariants(
  incomingVariants: string[],
  existingVariants: string[] | undefined,
): string[] | null {
  const resolved = incomingVariants.map((variant, index) => {
    if (!isRetainedCharacterAssetToken(variant)) {
      return variant;
    }

    return existingVariants?.[index] || '';
  });

  return resolved.every(isImageAssetReference) ? resolved : null;
}

function getTriggerKey(entity: { name: string; triggers?: string[] }): string {
  const triggers = (entity.triggers && entity.triggers.length > 0 ? entity.triggers : [entity.name])
    .map((trigger) => normalizeReactionName(trigger))
    .filter(Boolean);
  return triggers.join('|');
}

function findMatchingEntity<T extends { name: string; triggers?: string[] }>(
  entities: T[],
  target: { name: string; triggers?: string[] },
): T | undefined {
  const targetKey = getTriggerKey(target);
  return entities.find((entity) => getTriggerKey(entity) === targetKey);
}

async function resolveRetainedCharacterAssets(
  payload: ParsedCharacterPayload,
): Promise<ParsedCharacterPayload | null> {
  if (!hasRetainedCharacterAssets(payload)) {
    return payload;
  }

  if (!payload.id) {
    return null;
  }

  const state = await getStudioState();
  const existingCharacter = state.characters.find((character) => character.id === payload.id);
  if (!existingCharacter) {
    return null;
  }

  const sprites: Record<string, string[]> = {};
  for (const expression of SPRITE_EXPRESSIONS) {
    const resolvedVariants = resolveImageVariants(payload.sprites[expression] || [], existingCharacter.sprites[expression]);
    if (!resolvedVariants) {
      return null;
    }
    sprites[expression] = resolvedVariants;
  }

  const spriteDepthMaps: Record<string, string[]> = {};
  for (const expression of SPRITE_EXPRESSIONS) {
    const resolvedVariants = resolveImageVariants(
      payload.spriteDepthMaps[expression] || [],
      existingCharacter.spriteDepthMaps[expression],
    );
    if (!resolvedVariants) {
      return null;
    }
    spriteDepthMaps[expression] = resolvedVariants.slice(0, sprites[expression].length);
  }

  const spriteAnimationFrames: Record<string, { closedEyes: string[]; openMouth: string[] }> = {};
  for (const expression of SPRITE_EXPRESSIONS) {
    const existingFrames = existingCharacter.spriteAnimationFrames?.[expression];
    const incomingFrames = payload.spriteAnimationFrames[expression] || { closedEyes: [], openMouth: [] };
    const closedEyes = resolveImageVariants(incomingFrames.closedEyes || [], existingFrames?.closedEyes);
    const openMouth = resolveImageVariants(incomingFrames.openMouth || [], existingFrames?.openMouth);
    if (!closedEyes || !openMouth) {
      return null;
    }
    spriteAnimationFrames[expression] = {
      closedEyes: closedEyes.slice(0, sprites[expression].length),
      openMouth: openMouth.slice(0, sprites[expression].length),
    };
  }

  const customReactions = payload.customReactions.map((reaction) => {
    const existingReaction = findMatchingEntity(existingCharacter.customReactions, reaction);
    const sprites = resolveImageVariants(reaction.sprites, existingReaction?.sprites);
    const depthMaps = reaction.depthMaps
      ? resolveImageVariants(reaction.depthMaps, existingReaction?.depthMaps)
      : reaction.depthMaps;
    const animationFrames = reaction.animationFrames
      ? {
          closedEyes: resolveImageVariants(reaction.animationFrames.closedEyes, existingReaction?.animationFrames?.closedEyes),
          openMouth: resolveImageVariants(reaction.animationFrames.openMouth, existingReaction?.animationFrames?.openMouth),
        }
      : reaction.animationFrames;

    if (
      !sprites ||
      !depthMaps ||
      (animationFrames && (!animationFrames.closedEyes || !animationFrames.openMouth))
    ) {
      return null;
    }

    return {
      ...reaction,
      sprites,
      depthMaps,
      animationFrames: animationFrames
        ? {
            closedEyes: animationFrames.closedEyes!.slice(0, sprites.length),
            openMouth: animationFrames.openMouth!.slice(0, sprites.length),
          }
        : animationFrames,
    };
  });

  if (customReactions.some((reaction) => !reaction)) {
    return null;
  }

  const cgs = payload.cgs.map((cg) => {
    const existingCg = findMatchingEntity(existingCharacter.cgs, cg);
    const images = resolveImageVariants(cg.images, existingCg?.images);
    return images ? { ...cg, images } : null;
  });

  if (cgs.some((cg) => !cg)) {
    return null;
  }

  return {
    ...payload,
    sprites,
    spriteDepthMaps,
    spriteAnimationFrames,
    customReactions: customReactions as ParsedCharacterPayload['customReactions'],
    cgs: cgs as ParsedCharacterPayload['cgs'],
  };
}

function parseScenarioPayload(
  body: unknown,
): {
  id?: string;
  name: string;
  description: string;
  startMessage: string;
  specialInstructions: string;
  characterId: string;
  bannerDataUrl?: string;
  startSceneId?: string;
  startingPoints?: Array<{
    id?: string;
    name: string;
    sceneId: string;
    startMessage: string;
    specialInstructions: string;
  }>;
  scenes: Array<{
    id?: string;
    name: string;
    backgroundDataUrl: string;
    backgroundDepthMapDataUrl?: string;
    bgmDataUrl?: string;
    ambientNoiseDataUrl?: string;
    ambientNoisePresetId?: string;
    ambientNoiseMuffled?: boolean;
    weatherPreset?: SceneWeatherPreset;
    triggerWords: string[];
  }>;
} | null {
  if (!body || typeof body !== 'object') {
    return null;
  }

  const record = body as Record<string, unknown>;
  const name = asOptionalString(record.name)?.trim();
  const description = asOptionalString(record.description)?.trim() || '';
  const startMessage = asOptionalString(record.startMessage)?.trim() || '';
  const specialInstructions = asOptionalString(record.specialInstructions)?.trim() || '';
  const characterId = asOptionalString(record.characterId)?.trim();
  const bannerDataUrl = asOptionalString(record.bannerDataUrl)?.trim() || '';
  const startSceneId = asOptionalString(record.startSceneId)?.trim() || undefined;
  const id = asOptionalString(record.id)?.trim() || undefined;

  if (!name || !characterId) {
    return null;
  }

  if (bannerDataUrl && !isImageAssetReference(bannerDataUrl)) {
    return null;
  }

  const scenesRaw = Array.isArray(record.scenes) ? record.scenes : [];
  const scenes: Array<{
    id?: string;
    name: string;
    backgroundDataUrl: string;
    backgroundDepthMapDataUrl?: string;
    bgmDataUrl?: string;
    ambientNoiseDataUrl?: string;
    ambientNoisePresetId?: string;
    ambientNoiseMuffled?: boolean;
    weatherPreset?: SceneWeatherPreset;
    triggerWords: string[];
  }> = [];

  for (const scene of scenesRaw) {
    if (!scene || typeof scene !== 'object') {
      continue;
    }

    const sceneRecord = scene as Record<string, unknown>;
    const sceneId = asOptionalString(sceneRecord.id)?.trim() || undefined;
    const sceneName = asOptionalString(sceneRecord.name)?.trim();
    const backgroundDataUrl = asOptionalString(sceneRecord.backgroundDataUrl)?.trim();
    const backgroundDepthMapDataUrl =
      asOptionalString(sceneRecord.backgroundDepthMapDataUrl ?? sceneRecord.depthMapDataUrl)?.trim() || '';
    const bgmDataUrl = asOptionalString(sceneRecord.bgmDataUrl)?.trim() || '';
    const ambientNoiseDataUrl = asOptionalString(sceneRecord.ambientNoiseDataUrl)?.trim() || '';
    const ambientNoisePresetId = asOptionalString(sceneRecord.ambientNoisePresetId)?.trim() || '';
    const ambientNoiseMuffled = sceneRecord.ambientNoiseMuffled === true;
    const weatherPreset = parseSceneWeatherPreset(sceneRecord.weatherPreset);
    const triggerWords = parseTriggerWords(sceneRecord.triggerWords);

    if (!sceneName || !backgroundDataUrl || !isImageAssetReference(backgroundDataUrl)) {
      return null;
    }

    if (bgmDataUrl && !isAudioAssetReference(bgmDataUrl)) {
      return null;
    }

    if (ambientNoiseDataUrl && !isAudioAssetReference(ambientNoiseDataUrl)) {
      return null;
    }

    if (backgroundDepthMapDataUrl && !isImageAssetReference(backgroundDepthMapDataUrl)) {
      return null;
    }

    scenes.push({
      id: sceneId,
      name: sceneName,
      backgroundDataUrl,
      backgroundDepthMapDataUrl: backgroundDepthMapDataUrl || undefined,
      bgmDataUrl: bgmDataUrl || undefined,
      ambientNoiseDataUrl: ambientNoiseDataUrl || undefined,
      ambientNoisePresetId: ambientNoisePresetId || undefined,
      ambientNoiseMuffled,
      weatherPreset,
      triggerWords,
    });
  }

  if (scenes.length === 0) {
    return null;
  }

  const validSceneIds = new Set(scenes.map((scene) => scene.id).filter(Boolean) as string[]);
  const startingPointsRaw = Array.isArray(record.startingPoints) ? record.startingPoints : [];
  const startingPoints: Array<{
    id?: string;
    name: string;
    sceneId: string;
    startMessage: string;
    specialInstructions: string;
  }> = [];
  for (const rawPoint of startingPointsRaw) {
    if (!rawPoint || typeof rawPoint !== 'object') {
      continue;
    }

    const point = rawPoint as Record<string, unknown>;
    const pointId = asOptionalString(point.id)?.trim() || undefined;
    const pointName = asOptionalString(point.name)?.trim() || '';
    const pointSceneId = asOptionalString(point.sceneId)?.trim() || '';
    const pointStartMessage = asOptionalString(point.startMessage)?.trim() || '';
    const pointSpecialInstructions = asOptionalString(point.specialInstructions)?.trim() || '';
    if (!pointSceneId || !validSceneIds.has(pointSceneId)) {
      continue;
    }

    startingPoints.push({
      id: pointId,
      name: pointName || scenes.find((scene) => scene.id === pointSceneId)?.name || `Start ${startingPoints.length + 1}`,
      sceneId: pointSceneId,
      startMessage: pointStartMessage,
      specialInstructions: pointSpecialInstructions,
    });

    if (startingPoints.length >= 5) {
      break;
    }
  }

  if (startingPoints.length === 0 && scenes[0]?.id) {
    const fallbackSceneId = validSceneIds.has(startSceneId || '') ? startSceneId! : scenes[0].id;
    startingPoints.push({
      name: scenes.find((scene) => scene.id === fallbackSceneId)?.name || 'Default',
      sceneId: fallbackSceneId,
      startMessage: startMessage || '',
      specialInstructions,
    });
  }

  if (!startingPoints[0]?.startMessage.trim()) {
    return null;
  }

  return {
    id,
    name,
    description,
    startMessage,
    specialInstructions,
    characterId,
    bannerDataUrl: bannerDataUrl || undefined,
    startSceneId: scenes.some((scene) => scene.id === startSceneId) ? startSceneId : scenes[0]?.id,
    startingPoints,
    scenes,
  };
}

function parseRunCreatePayload(
  body: unknown,
): {
  scenarioId: string;
  title: string;
  messages: ScenarioRunMessage[];
  currentSceneId?: string;
  startingPointId?: string;
} | null {
  if (!body || typeof body !== 'object') {
    return null;
  }

  const record = body as Record<string, unknown>;
  const scenarioId = asOptionalString(record.scenarioId)?.trim();
  const title = asOptionalString(record.title)?.trim();
  const messages = parseMessagesArray(record.messages);
  const currentSceneId = asOptionalString(record.currentSceneId)?.trim() || undefined;
  const startingPointId = asOptionalString(record.startingPointId)?.trim() || undefined;

  if (!scenarioId || !title || !messages) {
    return null;
  }

  return {
    scenarioId,
    title,
    messages,
    currentSceneId,
    startingPointId,
  };
}

function slugifyFileName(value: string): string {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return normalized || 'package';
}

export { router as studioRouter };
